name: Build Discord Bot Docker Image

on:
  workflow_dispatch:
    inputs:
      latest:
        description: 'Add latest tag to built image'
        required: true
        default: false
        type: boolean
      latestTag:
        description: 'Existing tag to promote to latest e.g. 2023.11.01-01.01'
        required: true
        type: string
  push:
    paths:
      - 'src/**/*'
      - 'Dockerfile'
jobs:
  docker:
    name: Build & Push bot Develop Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ !inputs.latest }}
        uses: actions/checkout@v3
      - name: Docker Meta
        if: ${{ !inputs.latest }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/dfkhelper/discord-bot
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value={{ date 'YYYY.MM.DD-HH.mm' tz='America/Chicago' }},priority=950
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .npmrc file
        if: ${{ !inputs.latest }}
        run: |
          echo "@dfkhelper:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - name: Build and push
        if: ${{ !inputs.latest }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
      - name: Release
        if: ${{ inputs.latest }}
        run: |
          docker pull ghcr.io/dfkhelper/discord-bot:${{ inputs.latestTag }}
          docker tag ghcr.io/dfkhelper/discord-bot:${{ inputs.latestTag }} ghcr.io/dfkhelper/discord-bot:latest
          docker buildx imagetools create \
            --append \
            -t ghcr.io/dfkhelper/discord-bot:latest \
            ghcr.io/dfkhelper/discord-bot:${{ inputs.latestTag }}
